/* ------------------------------------------------------------------
   CONTENUTI — unica fonte di verità, IT + EN.
   Le chiavi sono identiche nelle due lingue. I valori con markup
   (<em>, <strong>, <br>) vengono inseriti come HTML, gli altri come testo.
   ------------------------------------------------------------------ */

export const SITE = {
  name: 'Andrea Gervasoni',
  fullName: 'Andrea Celeste Gervasoni',
  linkedin: 'https://www.linkedin.com/in/andrea-gervasoni-121639375',
  github: 'https://github.com/Andrea-Gervasoni',
  projects: {
    orizzonte: { live: 'https://andrea-gervasoni.github.io/Orizzonte-site/', code: 'https://github.com/Andrea-Gervasoni/Orizzonte-cpp' },
    formularium: { live: 'https://andrea-gervasoni.github.io/formularium/', code: 'https://github.com/Andrea-Gervasoni/formularium' }
  }
};

export const PHOTOS = [
  { id: 'la-jolla-sea-lion', it: 'Leoni marini sulla costa', en: 'Sea lions on the coast', w: 1050, h: 1400 },
  { id: 'sunset-cliffs',     it: 'Scogliere sull\u2019oceano',  en: 'Cliffs over the ocean',    w: 1050, h: 1400 },
  { id: 'balboa-museum',     it: 'Balboa Park · Museum of Us', en: 'Balboa Park · Museum of Us', w: 1050, h: 1400 },
  { id: 'palm-street',       it: 'Palme e semafori',          en: 'Palms and traffic lights',  w: 1050, h: 1400 },
  { id: 'zoo-koala',         it: 'Zoo · koala',               en: 'Zoo · koala',               w: 1050, h: 1400 },
  { id: 'downtown-towers',   it: 'Downtown',                  en: 'Downtown',                  w: 1050, h: 1400 },
  { id: 'balboa-fountain',   it: 'Balboa Park · la fontana',  en: 'Balboa Park · the fountain', w: 1050, h: 1400 },
  { id: 'charger',           it: 'Una Charger, ovviamente',   en: 'A Charger, obviously',      w: 1050, h: 1400 },
  { id: 'cliffs-palms',      it: 'La costa',                  en: 'The coast',                 w: 1050, h: 1400 },
  { id: 'zoo-meerkat',       it: 'Zoo · suricato',            en: 'Zoo · meerkat',             w: 1050, h: 1400 },
  { id: 'balboa-palms',      it: 'Balboa Park',               en: 'Balboa Park',               w: 1050, h: 1400 },
  { id: 'in-n-out',          it: 'In-N-Out · rito obbligatorio', en: 'In-N-Out · mandatory ritual', w: 1050, h: 1400 },
  { id: 'downtown-glass',    it: 'Downtown · vetro e cielo',  en: 'Downtown · glass and sky',  w: 1050, h: 1400 },
  { id: 'diner',             it: 'Una pausa',                 en: 'A break',                   w: 1050, h: 1400 }
];

export const TEXT = {
  it: {
    /* meta */
    'meta.title': 'Andrea Gervasoni — Studente, builder, TKS Innovator',
    'meta.description': 'Andrea Gervasoni, 17 anni, Bergamo. Studente del Liceo Scientifico, TKS Innovator 2026–27. Costruisco prodotti che rendono chiare le cose difficili.',
    'skip': 'Vai al contenuto',

    /* header / nav */
    'nav.about': 'Chi sono',
    'nav.projects': 'Progetti',
    'nav.experience': 'Esperienze',
    'nav.sandiego': 'San Diego',
    'nav.education': 'Formazione',
    'nav.skills': 'Competenze',
    'nav.languages': 'Lingue',
    'nav.contact': 'Contatti',
    'nav.menu': 'Menu',
    'nav.close': 'Chiudi',
    'nav.lang.aria': 'Switch to English',
    'nav.home.aria': 'Andrea Gervasoni, inizio',

    /* hero */
    'badge.aria': 'Tessera TKS Innovator 2026–2027',
    'badge.program': 'The Knowledge Society',
    'badge.role': 'Innovator',
    'badge.cohort': 'Coorte 2026 — 2027 · Bergamo',
    'badge.flip': 'TKS 2026 — 27',
    'badge.back.title': 'Dentro il programma',
    'badge.b1.k': 'Durata', 'badge.b1.v': '10 mesi · set 2026 — giu 2027',
    'badge.b2.k': 'Challenge', 'badge.b2.v': 'Prompt to Product · runner-up con Postilla',
    'badge.b3.k': 'Borsa', 'badge.b3.v': '$1.500 di scholarship',
    'badge.b4.k': 'Scuola', 'badge.b4.v': 'Liceo Scientifico L. Mascheroni',
    'hero.scroll': 'Scorri',
    'hero.avatar.aria': 'Ritratto 3D low-poly di Andrea che segue il cursore',

    /* note (chiusura) */
    'note.row1': 'Capire le cose difficili',
    'note.row2': 'BERGAMO · LICEO SCIENTIFICO · TKS INNOVATOR · STUDENTE',

    /* about */
    'about.kicker': '01 — Chi sono',
    'about.title': 'CHI SONO',
    'about.statement': 'Ho <em>17 anni</em>, vivo a <em>Bergamo</em> e frequento il Liceo Scientifico Mascheroni. Nel 2026–27 sono <em>TKS Innovator</em>. Costruisco prodotti che rendono chiare le cose difficili: <em>burocrazia</em>, <em>pensioni</em>, <em>matematica</em>.',
    'about.facts.label': 'In numeri',
    'about.fact1.n': '3',
    'about.fact1.l': 'prodotti costruiti e pubblicati',
    'about.fact2.n': '< 48 h',
    'about.fact2.l': 'da problema a prodotto funzionante (Postilla)',
    'about.fact3.n': '$1.500',
    'about.fact3.l': 'borsa di studio TKS · runner-up Prompt to Product',
    'about.fact4.n': '10 e lode',
    'about.fact4.l': 'esame di terza media',
    'about.focus.label': 'Oggi',
    'about.focus': 'AI e prodotto. Con TKS sto lavorando per trovare la mia strada definitiva: esploro ambiti diversi, costruisco, misuro.',

    /* projects */
    'projects.kicker': '02 — Progetti',
    'projects.title': 'PROGETTI',
    'projects.intro': 'Tre problemi reali, tre prodotti. Ogni oggetto qui sotto è vivo: trascinalo.',
    'projects.open': 'Apri la scheda',
    'projects.visit': 'Apri il sito',
    'projects.code': 'Codice',
    'projects.close': 'Chiudi',
    'projects.drag': 'Trascina per ruotare',
    'p1.name': 'Postilla',
    'p1.year': '2026',
    'p1.type': 'AI · documenti',
    'p1.tag': 'TKS Prompt to Product Challenge',
    'p1.deck': 'La burocrazia italiana, finalmente chiara. Postilla trasforma un documento ufficiale in un riepilogo comprensibile e nei passi da fare.',
    'p1.f1.k': 'Problema',
    'p1.f1.v': 'Documenti lunghi e confusi lasciano le persone senza sapere cosa fare, soprattutto chi è anziano o poco digitale.',
    'p1.f2.k': 'Cosa ho fatto',
    'p1.f2.v': 'Dal problema a un prodotto funzionante in meno di due giorni, interfaccia inclusa.',
    'p1.f3.k': 'Come funziona',
    'p1.f3.v': 'Analisi AI del documento in locale, riepilogo in linguaggio semplice, link diretto a pagoPA quando c’è da pagare.',
    'p1.f4.k': 'Risultato',
    'p1.f4.v': 'Runner-up della challenge e borsa di studio TKS da $1.500.',
    'p2.name': 'Orizzonte',
    'p2.year': '2026',
    'p2.type': 'Finanza · simulazione',
    'p2.tag': 'Motore C++ → prodotto JavaScript',
    'p2.deck': 'Un simulatore Monte Carlo per la pensione integrativa italiana: migliaia di futuri possibili invece di un unico numero.',
    'p2.f1.k': 'Domanda',
    'p2.f1.v': 'Come mostrare un futuro finanziario senza fingere che sia certo?',
    'p2.f2.k': 'Cosa ho fatto',
    'p2.f2.v': 'Un motore di simulazione in C++, poi tradotto in un prodotto web JavaScript.',
    'p2.f3.k': 'Come funziona',
    'p2.f3.v': 'Costi, tasse italiane e inflazione dentro migliaia di scenari: sfortunato, tipico, fortunato.',
    'p2.f4.k': 'Risultato',
    'p2.f4.v': 'Una distribuzione di probabilità in euro di oggi. Pubblicato e open source.',
    'p3.name': 'Formularium',
    'p3.year': '2026',
    'p3.type': 'Matematica · didattica',
    'p3.tag': 'JavaScript · KaTeX · JSXGraph',
    'p3.deck': 'Un formulario di matematica interattivo per il liceo scientifico: fatto per capire, non per memorizzare.',
    'p3.f1.k': 'Problema',
    'p3.f1.v': 'Le formule si imparano frammentate e senza contesto.',
    'p3.f2.k': 'Cosa ho fatto',
    'p3.f2.v': 'Per ogni argomento una scheda con formula, esempio svolto, errore comune, grafico interattivo e collegamenti.',
    'p3.f3.k': 'Come funziona',
    'p3.f3.v': 'Matematica composta con KaTeX, grafici vivi con JSXGraph, tutto in un’unica pagina pubblica.',
    'p3.f4.k': 'Risultato',
    'p3.f4.v': 'Uno strumento pubblico e interattivo, online per chiunque.',
    'p4.name': 'Il prossimo',
    'p4.year': '2026 →',
    'p4.type': 'In costruzione',
    'p4.deck': 'Con TKS sto lavorando a nuovi prototipi. Questo spazio si aggiorna con me.',

    /* experience */
    'exp.kicker': '03 — Esperienze',
    'exp.title': 'ESPERIENZE',
    'exp.intro': 'Cinque tappe, in ordine di tempo. Scorri: l\u2019aereo vola da una all\u2019altra.',
    'exp.legend': 'Scorri per volare',
    'e1.date': 'Marzo 2025',
    'e1.org': 'BABLE',
    'e1.role': 'Articolo per il magazine digitale di Bergamo',
    'e1.desc': 'Ricerca, scrittura e revisione di un pezzo per un pubblico giovane e curioso.',
    'e1.tag': 'Ricerca · scrittura',
    'e2.date': 'Aprile 2026',
    'e2.org': 'NN Editore',
    'e2.role': 'Scheda libro professionale',
    'e2.desc': 'Lettura critica, struttura editoriale e sintesi per una casa editrice.',
    'e2.tag': 'Analisi · editoria',
    'e3.date': 'Giugno 2026',
    'e3.org': 'Obton · Casei Gerola',
    'e3.role': 'Visita tecnica a un impianto fotovoltaico',
    'e3.desc': 'Raccolta e analisi dei dati di campo sul funzionamento e la resa dell’impianto.',
    'e3.tag': 'Energia · dati reali',
    'e4.date': 'Agosto 2026',
    'e4.org': 'San Diego, California',
    'e4.role': 'Vacanza studio di due settimane',
    'e4.desc': 'Corso e vita quotidiana in inglese, dall’altra parte del mondo.',
    'e4.tag': 'Inglese · autonomia',
    'e5.date': 'Set 2026 — Giu 2027',
    'e5.org': 'TKS · The Knowledge Society',
    'e5.role': 'Innovator',
    'e5.desc': 'Dieci mesi su tecnologie emergenti con progetti reali. Qui sto lavorando per trovare la mia strada definitiva.',
    'e5.tag': 'AI · prodotto · community globale',

    /* san diego */
    'sd.kicker': '04 — Diario',
    'sd.title': 'SAN DIEGO',
    'sd.sub': 'Vacanza studio · agosto 2026 · due settimane',
    'sd.quote': 'Due settimane di corso e vita quotidiana in inglese. Ma soprattutto le persone: compagni arrivati da tutto il mondo e conversazioni tra culture diverse. È la parte che mi è piaciuta di più.',
    'sd.quote2': 'Autonomia, una città nuova e parecchie foto storte.',
    'sd.prev': 'Foto precedente',
    'sd.next': 'Foto successiva',

    /* education */
    'edu.kicker': '05 — Formazione',
    'edu.title': 'FORMAZIONE',
    'edu.hint': 'Scorri: la pila cresce',
    'ed1.when': '2015 — 2020',
    'ed1.what': 'Scuola primaria \u201cG. Donizetti\u201d',
    'ed1.where': 'Bergamo',
    'ed1.note': 'Cinque anni. Le basi.',
    'ed2.when': '2020 — 2023',
    'ed2.what': 'Scuola media \u201cS. Alessandro\u201d',
    'ed2.where': 'Bergamo',
    'ed2.note': 'Esame di Stato: 10 e lode.',
    'ed3.when': '2023 — oggi',
    'ed3.what': 'Liceo Scientifico \u201cLorenzo Mascheroni\u201d',
    'ed3.where': 'Scienze Applicate · Bergamo · in corso',
    'ed3.note': 'Informatica, matematica, fisica, scienze naturali.',
    'ed4.when': '2026 — 2027',
    'ed4.what': 'The Knowledge Society',
    'ed4.where': 'TKS Innovator · dieci mesi, in parallelo al liceo',
    'ed4.note': 'Apprendimento per sfide, pensiero di prodotto, community internazionale.',
    'ed5.when': 'Certificazione',
    'ed5.what': 'Cambridge English B1 Preliminary',
    'ed5.where': 'Cambridge Assessment English',
    'ed5.note': 'Conseguita. Prossimo obiettivo: C1.',
    'ed6.when': 'Prossimo volume',
    'ed6.what': 'Universit\u00e0',
    'ed6.where': 'Ancora da scrivere',
    'ed6.note': 'La meta di tutto questo percorso.',

    /* skills */
    'sk.kicker': '06 — Competenze',
    'sk.title': 'COMPETENZE',
    'sk.intro': 'Sette discipline che uso insieme.',
    's1.n': 'Tecnologia', 's1.d': 'Strumenti AI · sviluppo web · C++ e JavaScript · prototipi', 's1.h': 'Trasformare una domanda in qualcosa che si può provare.',
    's2.n': 'Prodotto', 's2.d': 'Definizione del problema · iterazione · sistemi', 's2.h': 'Trovare l’attrito, inquadrarlo bene, migliorare con metodo.',
    's3.n': 'Design', 's3.d': 'UI · UX · direzione visiva · interazione', 's3.h': 'Rendere ciò che è utile chiaro e piacevole da usare.',
    's4.n': 'Business', 's4.d': 'Imprenditorialità · pitch · persuasione', 's4.h': 'Dare a un’idea una ragione per esistere oltre il prototipo.',
    's5.n': 'Leadership', 's5.d': 'Iniziativa · presentazione · coinvolgimento', 's5.h': 'Portare le persone dentro il ragionamento, non solo alla risposta.',
    's6.n': 'Analisi', 's6.d': 'Matematica · fisica · decisioni basate sui dati', 's6.h': 'Usare i numeri per mettere alla prova un’intuizione.',
    's7.n': 'Comunicazione', 's7.d': 'Ricerca · scrittura · chiarezza', 's7.h': 'Rendere leggibili le idee complesse a chi ne ha bisogno.',

    /* languages */
    'lang.kicker': '07 — Lingue',
    'lang.title': 'LINGUE',
    'l1.n': 'Italiano', 'l1.l': 'Madrelingua', 'l1.note': 'Leggo, scrivo, discuto. Anche troppo.',
    'l2.n': 'Inglese', 'l2.l': 'B2 in uso', 'l2.note': 'Cambridge B1 Preliminary certificato · obiettivo C1',
    'l3.n': 'Spagnolo', 'l3.l': 'A1', 'l3.note': 'Base',
    'l4.n': 'Cinese', 'l4.l': 'A1', 'l4.note': 'Una passione da sempre',
    'lang.legend.on': 'Raggiunto', 'lang.legend.cert': 'Certificato', 'lang.legend.goal': 'Obiettivo',

    /* scritti: Medium su un portatile 3D (anche le scritte dello schermo) */
    'nav.writing': 'Scritti',
    'wr.kicker': '08 — Scritti',
    'wr.title': 'SCRITTI',
    'wr.lead': 'Su Medium scrivo di AI, tecnologia e futuro: le storie vere dietro i titoli che girano, spiegate senza fumo.',
    'wr.topics': 'Di cosa scrivo',
    'wr.t1': 'AI', 'wr.t2': 'Tecnologia', 'wr.t3': 'Sicurezza', 'wr.t4': 'Futuro',
    'wr.s1.k': 'Il profilo', 'wr.s1.d': '@gervandre09, su Medium',
    'wr.s2.k': 'La bozza', 'wr.s2.d': 'un pezzo nuovo prende forma, riga dopo riga',
    'wr.s3.k': 'Pubblicato', 'wr.s3.d': 'esce su Medium: lo trovi lì, con gli altri',
    'wr.cta': 'Leggimi su Medium',
    'wr.scr.search': 'Cerca',
    'wr.scr.write': 'Scrivi',
    'wr.scr.home': 'Home', 'wr.scr.about': 'Info',
    'wr.scr.follow': 'Segui',
    'wr.scr.bio': 'Studente, builder, TKS Innovator. Scrivo di AI, tecnologia e futuro.',
    'wr.scr.draft': 'Bozza di Andrea Gervasoni',
    'wr.scr.publish': 'Pubblica',
    'wr.scr.published': 'Pubblicato su Medium',
    'wr.scr.phTitle': 'Titolo',
    'wr.scr.phBody': 'Racconta la tua storia…',
    'wr.scr.title': 'Perché scrivo',
    'wr.scr.body': 'Scrivo di AI e tecnologia quando la storia vera è più strana, e più precisa, del titolo che gira. Qui provo a raccontarla bene.',

    /* contact / footer */
    'ct.kicker': '09 — Contatti',
    'ct.title': 'PARLIAMONE',
    'ct.text': 'Vivo a Bergamo. Mi interessano le persone ambiziose e i problemi che vale la pena risolvere.',
    'ct.cta': 'Scrivimi su LinkedIn',
    'ft.statement': 'SEMPRE IN <em>COSTRUZIONE</em>.',
    'ft.pages': 'Pagine',
    'ft.follow': 'Trovami',
    'ft.copy': '© 2026 Andrea Gervasoni · Bergamo, Italia',
    'ft.made': 'Fatto a mano con Three.js, GSAP e un po’ di pazienza.',
    'ft.top': 'Torna su',
    'ft.wave': 'Clicca: ti saluto.'
  },

  en: {
    'meta.title': 'Andrea Gervasoni — Student, builder, TKS Innovator',
    'meta.description': 'Andrea Gervasoni, 17, Bergamo. Liceo Scientifico student, TKS Innovator 2026–27. I build products that make hard things clear.',
    'skip': 'Skip to content',

    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.experience': 'Experience',
    'nav.sandiego': 'San Diego',
    'nav.education': 'Education',
    'nav.skills': 'Skills',
    'nav.languages': 'Languages',
    'nav.contact': 'Contact',
    'nav.menu': 'Menu',
    'nav.close': 'Close',
    'nav.lang.aria': 'Passa all’italiano',
    'nav.home.aria': 'Andrea Gervasoni, home',

    'badge.aria': 'TKS Innovator 2026–2027 card',
    'badge.program': 'The Knowledge Society',
    'badge.role': 'Innovator',
    'badge.cohort': 'Cohort 2026 — 2027 · Bergamo',
    'badge.flip': 'TKS 2026 — 27',
    'badge.back.title': 'Inside the program',
    'badge.b1.k': 'Length', 'badge.b1.v': '10 months · Sep 2026 — Jun 2027',
    'badge.b2.k': 'Challenge', 'badge.b2.v': 'Prompt to Product · runner-up with Postilla',
    'badge.b3.k': 'Scholarship', 'badge.b3.v': '$1,500 award',
    'badge.b4.k': 'School', 'badge.b4.v': 'Liceo Scientifico L. Mascheroni',
    'hero.scroll': 'Scroll',
    'hero.avatar.aria': 'Low-poly 3D portrait of Andrea following the cursor',

    'note.row1': 'Making hard things clear',
    'note.row2': 'BERGAMO · LICEO SCIENTIFICO · TKS INNOVATOR · STUDENT',

    'about.kicker': '01 — About',
    'about.title': 'WHO I AM',
    'about.statement': 'I’m <em>17</em>, I live in <em>Bergamo</em> and I attend Liceo Scientifico Mascheroni. In 2026–27 I’m a <em>TKS Innovator</em>. I build products that make hard things clear: <em>paperwork</em>, <em>pensions</em>, <em>mathematics</em>.',
    'about.facts.label': 'In numbers',
    'about.fact1.n': '3',
    'about.fact1.l': 'products built and shipped',
    'about.fact2.n': '< 48 h',
    'about.fact2.l': 'from problem to working product (Postilla)',
    'about.fact3.n': '$1,500',
    'about.fact3.l': 'TKS scholarship · Prompt to Product runner-up',
    'about.fact4.n': '10 cum laude',
    'about.fact4.l': 'middle-school final exam',
    'about.focus.label': 'Today',
    'about.focus': 'AI and product. Through TKS I’m working to find my definitive path: exploring different fields, building, measuring.',

    'projects.kicker': '02 — Projects',
    'projects.title': 'PROJECTS',
    'projects.intro': 'Three real problems, three products. Every object below is alive: drag it.',
    'projects.open': 'Open the case',
    'projects.visit': 'Open the site',
    'projects.code': 'Code',
    'projects.close': 'Close',
    'projects.drag': 'Drag to rotate',
    'p1.name': 'Postilla',
    'p1.year': '2026',
    'p1.type': 'AI · documents',
    'p1.tag': 'TKS Prompt to Product Challenge',
    'p1.deck': 'Italian paperwork, finally clear. Postilla turns an official document into a plain summary and the steps to take.',
    'p1.f1.k': 'Problem',
    'p1.f1.v': 'Long, confusing documents leave people unsure how to act — especially older or less digital readers.',
    'p1.f2.k': 'What I did',
    'p1.f2.v': 'From problem to working product in under two days, interface included.',
    'p1.f3.k': 'How it works',
    'p1.f3.v': 'Local AI analysis of the document, a plain-language summary, a direct pagoPA link when there is something to pay.',
    'p1.f4.k': 'Result',
    'p1.f4.v': 'Challenge runner-up and a $1,500 TKS scholarship.',
    'p2.name': 'Orizzonte',
    'p2.year': '2026',
    'p2.type': 'Finance · simulation',
    'p2.tag': 'C++ engine → JavaScript product',
    'p2.deck': 'A Monte Carlo simulator for Italian supplementary pensions: thousands of possible futures instead of a single number.',
    'p2.f1.k': 'Question',
    'p2.f1.v': 'How do you show a financial future without pretending it is certain?',
    'p2.f2.k': 'What I did',
    'p2.f2.v': 'A simulation engine in C++, then translated into a JavaScript web product.',
    'p2.f3.k': 'How it works',
    'p2.f3.v': 'Fees, Italian taxes and inflation across thousands of scenarios: unlucky, typical, lucky.',
    'p2.f4.k': 'Result',
    'p2.f4.v': 'A probability distribution in today’s euros. Live and open source.',
    'p3.name': 'Formularium',
    'p3.year': '2026',
    'p3.type': 'Mathematics · learning',
    'p3.tag': 'JavaScript · KaTeX · JSXGraph',
    'p3.deck': 'An interactive mathematics formulary for liceo scientifico students: built for understanding, not memorising.',
    'p3.f1.k': 'Problem',
    'p3.f1.v': 'Formulas are learned fragmented and without context.',
    'p3.f2.k': 'What I did',
    'p3.f2.v': 'For each topic a card with formula, worked example, common mistake, interactive graph and connections.',
    'p3.f3.k': 'How it works',
    'p3.f3.v': 'Mathematics typeset with KaTeX, live graphs with JSXGraph, all in one public page.',
    'p3.f4.k': 'Result',
    'p3.f4.v': 'A public, interactive tool, online for anyone.',
    'p4.name': 'The next one',
    'p4.year': '2026 →',
    'p4.type': 'In progress',
    'p4.deck': 'Through TKS I’m working on new prototypes. This space updates as I do.',

    'exp.kicker': '03 — Experience',
    'exp.title': 'EXPERIENCE',
    'exp.intro': 'Five stops, in order of time. Scroll: the plane flies from one to the next.',
    'exp.legend': 'Scroll to fly',
    'e1.date': 'March 2025',
    'e1.org': 'BABLE',
    'e1.role': 'Article for the Bergamo digital magazine',
    'e1.desc': 'Research, writing and revision of a piece for a young, curious audience.',
    'e1.tag': 'Research · writing',
    'e2.date': 'April 2026',
    'e2.org': 'NN Editore',
    'e2.role': 'Professional book report',
    'e2.desc': 'Critical reading, editorial structure and synthesis for a publishing house.',
    'e2.tag': 'Analysis · publishing',
    'e3.date': 'June 2026',
    'e3.org': 'Obton · Casei Gerola',
    'e3.role': 'Technical visit to a photovoltaic plant',
    'e3.desc': 'Field data collection and analysis on the plant’s operation and output.',
    'e3.tag': 'Energy · real data',
    'e4.date': 'August 2026',
    'e4.org': 'San Diego, California',
    'e4.role': 'Two-week study holiday',
    'e4.desc': 'Classes and everyday life in English, on the other side of the world.',
    'e4.tag': 'English · independence',
    'e5.date': 'Sep 2026 — Jun 2027',
    'e5.org': 'TKS · The Knowledge Society',
    'e5.role': 'Innovator',
    'e5.desc': 'Ten months on emerging technologies with real projects. This is where I’m working to find my definitive path.',
    'e5.tag': 'AI · product · global community',

    'sd.kicker': '04 — Diary',
    'sd.title': 'SAN DIEGO',
    'sd.sub': 'Study holiday · August 2026 · two weeks',
    'sd.quote': 'Two weeks of classes and everyday life in English. Above all, the people: classmates from all over the world and conversations across cultures. The part I liked most.',
    'sd.quote2': 'Independence, a new city and quite a few crooked photos.',
    'sd.prev': 'Previous photo',
    'sd.next': 'Next photo',

    /* education */
    'edu.kicker': '05 — Education',
    'edu.title': 'EDUCATION',
    'edu.hint': 'Scroll: the stack grows',
    'ed1.when': '2015 — 2020',
    'ed1.what': 'Primary school \u201cG. Donizetti\u201d',
    'ed1.where': 'Bergamo',
    'ed1.note': 'Five years. The foundations.',
    'ed2.when': '2020 — 2023',
    'ed2.what': 'Middle school \u201cS. Alessandro\u201d',
    'ed2.where': 'Bergamo',
    'ed2.note': 'Final exam: 10 cum laude.',
    'ed3.when': '2023 — present',
    'ed3.what': 'Liceo Scientifico \u201cLorenzo Mascheroni\u201d',
    'ed3.where': 'Applied Sciences · Bergamo · ongoing',
    'ed3.note': 'Computer science, mathematics, physics, natural sciences.',
    'ed4.when': '2026 — 2027',
    'ed4.what': 'The Knowledge Society',
    'ed4.where': 'TKS Innovator · ten months, alongside school',
    'ed4.note': 'Challenge-based learning, product thinking, international community.',
    'ed5.when': 'Certification',
    'ed5.what': 'Cambridge English B1 Preliminary',
    'ed5.where': 'Cambridge Assessment English',
    'ed5.note': 'Achieved. Next goal: C1.',
    'ed6.when': 'Next volume',
    'ed6.what': 'University',
    'ed6.where': 'Still to be written',
    'ed6.note': 'Where this whole path is heading.',

    'sk.kicker': '06 — Skills',
    'sk.title': 'SKILLS',
    'sk.intro': 'Seven disciplines I use together.',
    's1.n': 'Technology', 's1.d': 'AI tools · web development · C++ and JavaScript · prototyping', 's1.h': 'Turn a question into something you can test.',
    's2.n': 'Product', 's2.d': 'Problem framing · iteration · systems', 's2.h': 'Find the friction, frame it precisely, improve with method.',
    's3.n': 'Design', 's3.d': 'UI · UX · visual direction · interaction', 's3.h': 'Make the useful thing clear and pleasant to use.',
    's4.n': 'Business', 's4.d': 'Entrepreneurship · pitching · persuasion', 's4.h': 'Give an idea a reason to exist beyond the prototype.',
    's5.n': 'Leadership', 's5.d': 'Initiative · presentation · bringing people in', 's5.h': 'Bring people into the thinking, not just the answer.',
    's6.n': 'Analysis', 's6.d': 'Mathematics · physics · data-led decisions', 's6.h': 'Use numbers to challenge a hunch.',
    's7.n': 'Communication', 's7.d': 'Research · writing · clarity', 's7.h': 'Make complex ideas legible for the people who need them.',

    'lang.kicker': '07 — Languages',
    'lang.title': 'LANGUAGES',
    'l1.n': 'Italian', 'l1.l': 'Native', 'l1.note': 'I read, write, argue. Maybe too much.',
    'l2.n': 'English', 'l2.l': 'B2 in use', 'l2.note': 'Cambridge B1 Preliminary certified · aiming for C1',
    'l3.n': 'Spanish', 'l3.l': 'A1', 'l3.note': 'Basics',
    'l4.n': 'Chinese', 'l4.l': 'A1', 'l4.note': 'A lifelong passion',
    'lang.legend.on': 'Reached', 'lang.legend.cert': 'Certified', 'lang.legend.goal': 'Goal',

    'nav.writing': 'Writing',
    'wr.kicker': '08 — Writing',
    'wr.title': 'WRITING',
    'wr.lead': 'On Medium I write about AI, technology and the future: the real stories behind the headlines going around, explained without the smoke.',
    'wr.topics': 'What I write about',
    'wr.t1': 'AI', 'wr.t2': 'Technology', 'wr.t3': 'Security', 'wr.t4': 'Future',
    'wr.s1.k': 'The profile', 'wr.s1.d': '@gervandre09, on Medium',
    'wr.s2.k': 'The draft', 'wr.s2.d': 'a new piece takes shape, line by line',
    'wr.s3.k': 'Published', 'wr.s3.d': 'it goes out on Medium: find it there, with the others',
    'wr.cta': 'Read me on Medium',
    'wr.scr.search': 'Search',
    'wr.scr.write': 'Write',
    'wr.scr.home': 'Home', 'wr.scr.about': 'About',
    'wr.scr.follow': 'Follow',
    'wr.scr.bio': 'Student, builder, TKS Innovator. I write about AI, technology and the future.',
    'wr.scr.draft': 'Draft by Andrea Gervasoni',
    'wr.scr.publish': 'Publish',
    'wr.scr.published': 'Published on Medium',
    'wr.scr.phTitle': 'Title',
    'wr.scr.phBody': 'Tell your story…',
    'wr.scr.title': 'Why I write',
    'wr.scr.body': 'I write about AI and technology when the real story is stranger, and more specific, than the headline going around. Here I try to tell it well.',

    'ct.kicker': '09 — Contact',
    'ct.title': 'LET’S TALK',
    'ct.text': 'Based in Bergamo. Interested in ambitious people and problems worth solving.',
    'ct.cta': 'Message me on LinkedIn',
    'ft.statement': 'ALWAYS <em>BUILDING</em>.',
    'ft.pages': 'Pages',
    'ft.follow': 'Find me',
    'ft.copy': '© 2026 Andrea Gervasoni · Bergamo, Italy',
    'ft.made': 'Handmade with Three.js, GSAP and some patience.',
    'ft.top': 'Back to top',
    'ft.wave': 'Click: I’ll wave.'
  }
};

/* Parole che il titolo "Lingue" attraversa prima di fermarsi */
export const LANGUAGE_MORPH = ['LINGUE', 'LANGUAGES', 'IDIOMAS', '语言'];
